name: vul_lib
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.10.0
  - pip=24.2
  - pip: 
    - numpy==2.1.1
    - pandas==2.2.2
    - transformers==4.44.2
    - scikit-learn==1.5.2
    - torch==2.4.1